src/wamytmapp/urls.py
from django.urls import include, path

from . import views
from .admin import korporator_admin

app_name = "wamytmapp"
urlpatterns = [
    path('', views.index, name='index'),
    path('ical/a/ou-<int:orgunit>.ics', views.TeamFeed(), name='icalfeed-by-orgunit'),
    path('survey', views.weekCSV, name='weekCSV'),
    path('add', views.add, name='add'),
    path('list', views.list1, name='list1'),
    path('profile', views.profile, name="profile"),
    path('timeranges', views.TimeRangesList.as_view()),
    path('check', views.conflict_check),
    path('getorgid', views.getorgid),
]

src/wamytmapp/forms.py
from django import forms
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import User
from django.utils.translation import pgettext_lazy

from .fields import OverlapActionsField
from .models import mv_odb_org, OrgUnit, OrgUnitDelegate, TimeRange, TeamMember, user_display_name, OMS, ODB_STRUKT
from .config import RuntimeConfig


class DateInput(forms.DateInput):
    input_type = 'date'

class orgs4wamytmEditForm(forms.ModelForm):
    ko_m = forms.ChoiceField(
        required=True,
        #choices = ODB_STRUKT.objects.SelectList_with_Orgs(),
        label=pgettext_lazy('OrgUnitFilterForm', 'Organizational unit'))
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['ko_m'].choices = ODB_STRUKT.objects.SelectList_with_Orgs()

class TimeRangeEditForm(forms.ModelForm):
    description = forms.CharField(
        max_length=150,
        required=False,
        label=pgettext_lazy('AddTimeRangeForm', 'Description'))
    part_of_day = forms.ChoiceField(
        help_text=pgettext_lazy(
            'AddTimeRangeForm', 'Entry can be associated to a part of the day'),
        label=pgettext_lazy('AddTimeRangeForm', 'Partial entry'),
        required=False,
        choices=[
            (None, pgettext_lazy('AddTimeRangeForm', 'Whole day')),
            ('f', pgettext_lazy('AddTimeRangeForm', 'Forenoon')),
            ('a', pgettext_lazy('AddTimeRangeForm', 'Afternoon'))
        ])
    subkind = forms.ChoiceField(
        required=True,
        label=pgettext_lazy('AddTimeRangeForm', 'Kind of time range'),
        choices=RuntimeConfig().TimeRangeChoices)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = kwargs['instance']
        if instance and instance.data:
            if 'v' in instance.data:
                if TimeRange.DATA_DESCRIPTION in instance.data:
                    self.fields['description'].initial = instance.data[TimeRange.DATA_DESCRIPTION]
                if TimeRange.DATA_PARTIAL in instance.data:
                    self.fields['part_of_day'].initial = instance.data[TimeRange.DATA_PARTIAL]
        self.fields['subkind'].initial = instance.kind + "_"

    class Meta:
        model = TimeRange
        fields = ['org', 'start', 'end', 'subkind',
                  'part_of_day', 'description', 'user']

    def clean(self):
        super().clean()
        cleaned_data = self.cleaned_data
        complexKind = cleaned_data['subkind']
        cleaned_data['kind'] = complexKind[:1]
        jsondata = {'v': 1}
        if 'description' in cleaned_data and cleaned_data['description'] != '':
            jsondata[TimeRange.DATA_DESCRIPTION] = cleaned_data['description']
        if 'part_of_day' in cleaned_data and cleaned_data['part_of_day'] != '':
            jsondata[TimeRange.DATA_PARTIAL] = cleaned_data['part_of_day']
        self.cleaned_data['data'] = jsondata

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.data = self.cleaned_data['data']
        instance.kind = self.cleaned_data['kind']
        return super().save(commit)


class AddTimeRangeForm(forms.Form):
    """
        A form to add a new time range entry.
    """
    dateInputAttrs = {
        'data-provide': 'datepicker',
        'data-date-calendar-weeks': 'true',
        'data-date-format': 'yyyy-mm-dd',
        'data-date-today-highlight': 'true',
        'data-date-week-start': '1',
        'data-date-today-btn': 'true'
    }
    required_css_class = 'required'
    user = forms.ChoiceField(
        label=pgettext_lazy('AddTimeRangeForm', 'User'),
        disabled=True,
        required=False)
    start = forms.DateField(
        label=pgettext_lazy('AddTimeRangeForm', 'Start'),
        required=True,
        widget=forms.widgets.DateInput(attrs=dateInputAttrs))
    end = forms.DateField(
        label=pgettext_lazy('AddTimeRangeForm', 'End'),
        required=False,
        help_text=pgettext_lazy('AddTimeRangeForm',
                                'If left blank, it will be set to start date'),
        widget=forms.widgets.DateInput(attrs=dateInputAttrs))
    #orgunit_id = forms.ChoiceField(
    org_id = forms.ChoiceField(
        required=True,
        disabled=False,
        help_text=pgettext_lazy(
            'AddTimeRangeForm', 'Entry will be visible to this and all organizational units above'),
        label=pgettext_lazy('AddTimeRangeForm', 'Organizational unit'))
    kind = forms.ChoiceField(
        help_text=pgettext_lazy('AddTimeRangeForm', 'kind_help'),
        required=True,
        label=pgettext_lazy('AddTimeRangeForm', 'Kind of time range'))
    description = forms.CharField(
        max_length=150,
        required=False,
        label=pgettext_lazy('AddTimeRangeForm', 'Description'))
    part_of_day = forms.ChoiceField(
        help_text=pgettext_lazy(
            'AddTimeRangeForm', 'Entry can be associated to a part of the day'),
        label=pgettext_lazy('AddTimeRangeForm', 'Partial entry'),
        required=False,
        choices=[
            (None, pgettext_lazy('AddTimeRangeForm', 'Whole day')),
            ('f', pgettext_lazy('AddTimeRangeForm', 'Forenoon')),
            ('a', pgettext_lazy('AddTimeRangeForm', 'Afternoon'))
        ])
    overlap_actions = OverlapActionsField(
        required=False
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.can_delegate = self.user.orgunitdelegate_set.count() > 0
        super(AddTimeRangeForm, self).__init__(*args, **kwargs)
        self.fields['user'].initial = self.user.id
        self.fields['user'].choices = [(self.user.id, user_display_name(self.user))]


        #self.fields['orgunit_id'].choices = odb_org.objects.selectListItemsWithAllChoice()
        self.fields['org_id'].choices = mv_odb_org.objects.selectListItemsWithAllChoice()
        M2O_ORG_ID = OMS.objects.getORG_ID(self.user.id)
        if M2O_ORG_ID is not None:
            #self.fields['orgunit_id'].initial = M2O_ORG_ID.M2O_ORG_ID
            self.fields['org_id'].initial = M2O_ORG_ID.m2o_org_id
            #self.fields['orgunit_id'].disabled = True
            self.fields['org_id'].disabled = True
        
        self._setupKindChoices()
        if self.can_delegate:
            userfield = self.fields['user']
            userfield.disabled = False
            userfield.required = True
            #list2 = list(map(lambda u: (u[0], F"{u[2]}, {u[1]} ({u[3]} ({u[4]}))"), OrgUnitDelegate.objects.delegatedUsers2(self.user.id)))
            list2 = list(map(lambda u: (u[0], F"{u[2]}, {u[1]}"), OrgUnitDelegate.objects.delegatedUsers2(self.user.id)))
            userfield.choices = sorted(list(dict.fromkeys(userfield.choices + list2)), key=lambda tup: tup[1])

    def get_time_range(self):
        if self.is_valid() == False:
            return None

        cleaned_data = self.cleaned_data

        if self.can_delegate:
            cleaned_data['user_id'] = cleaned_data['user']
            cleaned_data['org_id'] = OMS.objects.getORG_ID(cleaned_data['user_id']).m2o_org_id
        else:
            cleaned_data['user_id'] = self.user.id

        del(cleaned_data['user'])

        complexKind = cleaned_data['kind']
        cleaned_data['kind'] = complexKind[:1]
        jsondata = {'v': 1}
        if complexKind[1:] != RuntimeConfig.KIND_DEFAULT:
            jsondata[TimeRange.DATA_KINDDETAIL] = complexKind[1:]
        if 'description' in cleaned_data and cleaned_data['description'] != '':
            jsondata[TimeRange.DATA_DESCRIPTION] = cleaned_data['description']
        if 'part_of_day' in cleaned_data and cleaned_data['part_of_day'] != '':
            jsondata[TimeRange.DATA_PARTIAL] = cleaned_data['part_of_day']
        initData = {
            'user_id': cleaned_data['user_id'],
            #'orgunit_id': cleaned_data['orgunit_id'],
            'org_id': cleaned_data['org_id'],
            'start': cleaned_data['start'],
            'end': cleaned_data['end'],
            'kind': complexKind[:1],
            'data': jsondata
        }
        return TimeRange(**initData)

    def _setupKindChoices(self):
        self.fields['kind'].choices = RuntimeConfig().TimeRangeChoices


class FrontPageFilterForm(forms.Form):
    embed = forms.BooleanField(required=False, widget=forms.HiddenInput())
    weekdelta = forms.IntegerField(required=False, widget=forms.HiddenInput())
    users = forms.CharField(required=False, widget=forms.HiddenInput())
    orgunit = forms.ChoiceField(
        required=False,
        widget=forms.Select(
            attrs={'onchange': 'submitFilter();'}
        ),
        label=pgettext_lazy('OrgUnitFilterForm', 'Organizational unit'))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['orgunit'].choices = mv_odb_org.objects.selectListItemsWithAllChoice()

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['weekdelta'] is None:
            cleaned_data['weekdelta'] = 0


class OrgUnitFilterForm(forms.Form):
    embed = forms.BooleanField(required=False, widget=forms.HiddenInput())
    fd = forms.CharField(required=False, widget=forms.HiddenInput())
    td = forms.CharField(required=False, widget=forms.HiddenInput())
    orgunit = forms.ChoiceField(
        required=False,
        widget=forms.Select(
            attrs={'onchange': 'filterform.submit();'}
        ),
        label=pgettext_lazy('OrgUnitFilterForm', 'Organizational unit'))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #self.fields['orgunit'].choices = OrgUnit.objects.selectListItemsWithAllChoice()
        self.fields['orgunit'].choices = mv_odb_org.objects.selectListItemsWithAllChoice()


class ProfileForm(forms.Form):
    orgunit = forms.ChoiceField(
        required=True,
        help_text=pgettext_lazy(

src/wamytmapp/templates/wamytmapp/add.html
{% extends 'wamytmapp/base.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap4 %}

{% block content %}

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">{% trans "New entry" context "AddTimeRangeForm" %}</h1>
        <p class="lead">{% trans "A new date can be added." context "AddTimeRangeForm" %}</p>
    </div>
</div>

{% bootstrap_form_errors form layout='inline' %}
<form action="{% url 'wamytmapp:add' %}" method="post" role="form">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-7">
            {% bootstrap_field form.start %}
            {% bootstrap_field form.end %}
        </div>
        <div class="col-md-5">
            {% bootstrap_field form.user %}
            {% bootstrap_field form.org_id %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-7">
            {% bootstrap_field form.kind %}
            {% bootstrap_field form.description %}
        </div>
        <div class="col-md-5">
            {% bootstrap_field form.part_of_day %}
        </div>
    </div>
    <div class="row" style="display: none;" id="overlappingcontainer">
        <div class="col-md-12">
            {% trans "Overlapping items" context "AddTimeRangeForm" %}
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">{% trans "Begin date" context "AddTimeRangeFormOverlapTable" %}</th>
                        <th scope="col">{% trans "End date" context "AddTimeRangeFormOverlapTable" %}</th>
                        <th scope="col">{% trans "Kind" context "AddTimeRangeFormOverlapTable" %}</th>
                        <th scope="col">{% trans "Partial" context "AddTimeRangeFormOverlapTable" %}</th>
                        <th scope="col">{% trans "Action" context "AddTimeRangeFormOverlapTable" %}</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
    <div class="row">
    <div class="col-12">
    {% buttons %}
    <button type="submit" class="btn btn-primary">
        <span id="submitspinner" class="spinner-border spinner-border-sm" role="status" aria-hidden="true" style="display: none;"></span>
        {% trans "Submit" context "AddTimeRangeForm" %}
    </button>
    <a href="{% url 'wamytmapp:index' %}" class="btn btn-secondary">{% trans "Cancel" context "AddTimeRangeForm" %}</a>
    {% endbuttons %}
    </div>
    </div>
</form>
<script>
    wamytmi18n['res_beg'] = '{% trans "Set new start date" context "AddTimeRangeForm" %}';
    wamytmi18n['res_end'] = '{% trans "Set new end date" context "AddTimeRangeForm" %}';
    wamytmi18n['res_spl'] = '{% trans "Split item" context "AddTimeRangeForm" %}';
    wamytmi18n['res_del'] = '{% trans "Delete item" context "AddTimeRangeForm" %}';
</script>
<script src="{% static 'wamytmapp/js/add.js' %}"></script>
{% endblock %}

src/wamytmapp/templates/wamytmapp/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html>

<head>
    <title>{% trans "Korporator" context "BaseTemplate" %}</title>
    <script src="{% static 'wamytmapp/js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'wamytmapp/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'wamytmapp/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'wamytmapp/js/hierarchy-select.min.js' %}"></script>
    <script src="{% static 'wamytmapp/js/bootstrap-datepicker.de.min.js' %}"></script>
    <script src="{% static 'wamytmapp/js/hierarchy-select.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'wamytmapp/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'wamytmapp/css/bootstrap-datepicker.standalone.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'wamytmapp/css/hierarchy-select.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'wamytmapp/css/style.css' %}">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'wamytmapp/css/bootstrap-icons.css' %}">-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'wamytmapp/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'wamytmapp/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'wamytmapp/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'wamytmapp/favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'wamytmapp/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script>
        const wamytmroot = "{% url 'wamytmapp:index' %}";
        const wamytmi18n = {};
    </script>
</head>

<body{% if embeded %} class="embedded" {% endif %}>
    <div class="content container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light hide-embedded">
            <a class="navbar-brand" href="{% url 'wamytmapp:index' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 20 20">
                    <path d="M0 0h20v20H0z" fill="#ccc" fill-opacity=".992" paint-order="fill markers stroke" />
                    <path
                        d="M15.127 1.763l-2.102.025c-3.27 2.907-5.45 4.68-8.75 7.546l-1.283 9.95h3.86l-.05-4.22 5.885 4.197 4.325.028-10.16-8.737v-.057zM4.274.813v5.603L6.85 4.182V.376z"
                        fill="#00ab00" fill-opacity=".992" paint-order="fill markers stroke" /></svg>
                {% trans "Korporator" context "BaseTemplate" %}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link"
                        href="{% url 'wamytmapp:add' %}">{% trans "Add date" context "BaseTemplate" %}</a>
                    <a class="nav-item nav-link"
                        href="{% url 'wamytmapp:list1' %}">{% trans "3 months ahead view" context "BaseTemplate" %}</a>
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link"
                        href="{% url 'ka:index' %}">{% trans "Administration" context "BaseTemplate" %}</a>
                    {% endif %}
                </div>
            </div>
        </nav>
        <div class="row">
            <div class="col-md-12">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

    {% include 'wamytmapp/footer.html' %}

    </body>

</html>

src/wamytmapp/templates/wamytmapp/footer.html
{% load i18n %}
<footer id="footer" class="border-top bg-light hide-embedded">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center">
                <p class="h6">Version: 2020-03-29 <a class="ml-2" href="https://github.com/erikwegner/wamytm"
                        target="_blank">Issues, Code, Credits</a></p>
            </div>
        </div>
    </div>
</footer>
<script>
    $(function () {

        $('.partial-f').each(function (n, e) {
            $(e).prop('title', '{% trans "Forenoon" context "Tooltip" %}');
        });
        $('.partial-a').each(function (n, e) {
            $(e).prop('title', '{% trans "Afternoon" context "Tooltip" %}');
        });
        $('[data-toggle="tooltip"]').tooltip();
    });

</script>

src/wamytmapp/templates/wamytmapp/list1.html
{% extends 'wamytmapp/base.html' %}
{% load bootstrap4 %}
{% load get_value_from_dict %}
{% load get_partial_symbol %}
{% load get_description_tooltip %}
{% load i18n %}

{% block content %}

<form action="{% url 'wamytmapp:list1' %}" method="get" class="mb-3" role="form" id="filterform">
    <label for="id_orgunit">Organisationseinheit</label>
    {% if embeded %}{% bootstrap_field ouselect.embed %}{% endif %}
    <div class="dropdown hierarchy-select" id="id_orgunit">
        <button type="button" class="btn btn-secondary dropdown-toggle" id="example-three-button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
        <div class="dropdown-menu" aria-labelledby="example-three-button">
            <div class="hs-searchbox">
                <input type="text" class="form-control" autocomplete="off">
            </div>
            <div class="hs-menu-inner">
                <a class="dropdown-item" data-value="0" data-level="1" href="#">Alle</a>
                {% for em in orgunit_filter %}
                    <a class="dropdown-item" data-value="{{ em.id }}" data-level="{{ em.lvl }}" href="#">{{ em.name }}</a>
                {% endfor %}
            </div>
        </div>
        <input class="d-none" name="orgunit" readonly="readonly" aria-hidden="true" type="text" value="{{ orgunit }}" />
    </div>
    <input name="orgunit_initial" readonly="readonly" type="hidden" value="{{ orgunit_initial }}" />
    {% bootstrap_field ouselect.fd %}
    {% bootstrap_field ouselect.td %}
</form>

{% spaceless %}
<table class="table table-sm presence">
    {% for line in lines %}
    {% if forloop.counter0 == 0 or forloop.counter0 > 8 and line.start_of_week and line.four_week_counter == 1 %}
    {% if forloop.counter0 > 0 %}
    </tbody>
    {% endif %}
    <thead>
        <tr class="bg-secondary">
            <th scope="col">{% trans "Date" context "List1Template" %}</th>
            {% for user in users %}
                <th scope="col">{{ user.display_name }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
    {% endif %}
        <tr class="{% if line.week_is_even %}bg-light {% endif %}{% if line.start_of_week %}start-of-week {% endif %}">
            <th scope="row"{% if line.day.allday %} class="allday"{% endif %}>{{ line.day.day | date:"d. M (D)" }}{% if line.day.allday %} {{ line.day.allday.description }}{% endif %}</th>
            {% for col in line.cols %}
            {% if col %}
            <td class="kind-{{ col.new_kind }}">{% with col.kind_with_details as k %}{{ trc|get_value_from_dict:k }}{% endwith %}{{ col.data|get_description_tooltip}}</td>
            {% else %}
            <td></td>
            {% endif %}
            {% endfor %}
        </tr>
    {% if forloop.last %}
    </tbody>
    {% endif %}
    {% endfor %}
</table>
{% endspaceless %}

{% if orgunit_initial > 0 %}
    <a class="hide-embedded" href="{% url 'wamytmapp:icalfeed-by-orgunit' orgunit=orgunit %}" role="">{% trans "iCal calendar sync" context "IndexTemplate" %}</a>
{% endif %}
<script>
    $('#id_orgunit').hierarchySelect({
        width: '100%',
        height: '500px',
        resetSearchOnSelection: false,
        initialValueSet: true,
        onChange: function (value) {
            if ($('input[name=orgunit_initial]').val() != value) {
                document.getElementById('filterform').submit();
            }
        }
    });
</script>
{% endblock %}

src/wamytmapp/templates/wamytmapp/profile.html
{% extends 'wamytmapp/base.html' %}
{% load bootstrap4 %}
{% load i18n %}

{% block content %}

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">{% trans "Profile" context "ProfileTemplate" %}</h1>
        <p class="lead">{% trans "Account settings." context "ProfileTemplate" %}</p>
    </div>
</div>

{% bootstrap_form_errors form layout='inline' %}
<form action="{% url 'wamytmapp:profile' %}" method="post" role="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
        {% trans "Submit" context "ProfileTemplate" %}
    </button>
    <a href="{% url 'wamytmapp:index' %}" class="btn btn-secondary">{% trans "Cancel" context "ProfileTemplate" %}</a>
    {% endbuttons %}
</form>

{% endblock %}